# Site settings
title: dgms code
email: dgmstuart@gmail.com
description: >
  This is the dev blog of Duncan Graeme Macdonald Stuart - a Technical
  Architect living in London. The focus is mostly Ruby on Rails 
  with a little WordPress
url: "http://dgmstuart.github.io"
twitter_username: dgmstuart
github_username:  dgmstuart

# Build settings
markdown: kramdown
