# Site settings
title: dgms code
email: dgmstuart@gmail.com
description: >
  This is the dev blog of Duncan Graeme Macdonald Stuart - a Technical
  Architect living in London. The focus is mostly Ruby on Rails 
  with a little WordPress
url: "http://dgmstuart.github.io"
twitter_username: dgmstuart
github_username:  dgmstuart
disqus_shortname: dgmscode

google_analytics_code: UA-44436648-5

# Build settings
markdown: kramdown

# Octopress 2-style permalink:
permalink: /blog/:year/:month/:day/:title/
